language: node_js
node_js: 8

before_deploy:
  - cd dist

stages:
  - name: deploy
    # require the branch name to be master (note for PRs this is the base branch name)
    if: branch = prod
    script: npm run build
    deploy:
    - provider: npm
      tag: latest
      all_branches: true
      skip_cleanup: true
      email: $NPM_EMAIL
      api_key: $NPM_TOKEN

stages:
  - name: deploy
    # require the branch name to be master (note for PRs this is the base branch name)
    if: branch = prod
    script: npm run build:next
    deploy:
    - provider: npm
      tag: next
      all_branches: true
      skip_cleanup: true
      email: $NPM_EMAIL
      api_key: $NPM_TOKEN
