language: node_js
node_js: 8
before_deploy:
  - npm run build && cd dist
deploy:
  - provider: npm
    on:
      branch: prod
    skip_cleanup: true
    email: riksheim.leif@gmail.com
    api_key:
      secure: caKMWVlNLhakiowXHtH/CUiClekWGF11NlwSpifWDtkMQkEyP0rIfYIZzH+v4uUUiJqsFP3YID8C30g56RuMqqjCra628lVyWD6zySxFjGMZRGl0KrP+HCqcMatzEox20l2WpKNWBKMv3ORFHkYRpKWBUOZge23SQqBBnmnjAnxYAIkaq+QeLIN1kBs4O8uAXjbhh/teftKjqJw3umaCoedLvn16e2FEjPsAEhPR2rant8n7AbTTaJ1CVVkajlGJ0hpWEqxBMx/o2//wUD5wxHI6w1kyDinsKfrNhfcVPTHv4H13iQSXCM+o6P63b1flGzrjM9jzwi2WubZ26uW9eBfCmr1fTQ6z/tCNhX1hci3QTmav134cszeUrSQNmaFknEGo/uOl8zzDoaJ147YPFbiF8fBimULjr7suuhaEU9L20/IW4tqFgn0I4YmLNatcEc1NGtu4WwEtfs9SyobrRDZyJPd7dr1547PeuIzKwbwAAUEl8dzgDCPhK9B0M9Mj/s73sbo/yitZiiKkf57ksRIU7wnHfNx3Meago47QLgYwWVgNuBClC+igCDLGu9nPF+LQG3zJR5QI8TPAngc1uO0AoEUb7zKDscz/c7kr1e/pDFMZf1no6SlXpJqCmCC3RyYG59mMuIMdSXZPxdTHhzbO3bdDEGHyF5phRiYnEyw=
  - provider: npm
    on:
      branch: master
    skip_cleanup: true
    email: riksheim.leif@gmail.com
    tag: next
    api_key:
      secure: caKMWVlNLhakiowXHtH/CUiClekWGF11NlwSpifWDtkMQkEyP0rIfYIZzH+v4uUUiJqsFP3YID8C30g56RuMqqjCra628lVyWD6zySxFjGMZRGl0KrP+HCqcMatzEox20l2WpKNWBKMv3ORFHkYRpKWBUOZge23SQqBBnmnjAnxYAIkaq+QeLIN1kBs4O8uAXjbhh/teftKjqJw3umaCoedLvn16e2FEjPsAEhPR2rant8n7AbTTaJ1CVVkajlGJ0hpWEqxBMx/o2//wUD5wxHI6w1kyDinsKfrNhfcVPTHv4H13iQSXCM+o6P63b1flGzrjM9jzwi2WubZ26uW9eBfCmr1fTQ6z/tCNhX1hci3QTmav134cszeUrSQNmaFknEGo/uOl8zzDoaJ147YPFbiF8fBimULjr7suuhaEU9L20/IW4tqFgn0I4YmLNatcEc1NGtu4WwEtfs9SyobrRDZyJPd7dr1547PeuIzKwbwAAUEl8dzgDCPhK9B0M9Mj/s73sbo/yitZiiKkf57ksRIU7wnHfNx3Meago47QLgYwWVgNuBClC+igCDLGu9nPF+LQG3zJR5QI8TPAngc1uO0AoEUb7zKDscz/c7kr1e/pDFMZf1no6SlXpJqCmCC3RyYG59mMuIMdSXZPxdTHhzbO3bdDEGHyF5phRiYnEyw=
