language: node_js
node_js: 8

script:
  - "$TRAVIS_BRANCH" = "master" && npm run build:next
  - "$TRAVIS_BRANCH" = "prod" && npm run build

before_deploy:
  - cd dist

deploy:
  - provider: npm
    tag: latest
    on:
      branch: prod
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
  - provider: npm
    tag: next
    on:
      branch: master
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
