language: node_js
node_js: 8

script: npm run build

before_deploy:
  - cd dist

deploy:
  - provider: npm
    tag: latest
    script: npm run build
    on:
      branch: prod
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
  - provider: npm
    tag: next
    script: npm run build:next
    on:
      branch: master
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
