language: node_js
node_js: 8
script: npm run build
before_deploy:
  - cd dist
deploy:
  - provider: npm
    on:
      branch: prod
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
  - provider: npm
    on:
      branch: master
    skip_cleanup: true
    email: riksheim.leif@gmail.com
    tag: next
    api_key: $NPM_TOKEN
