language: node_js
node_js: 8

script:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then npm run build:next; fi
  - if [ "$TRAVIS_BRANCH" = "prod" ]; then npm run build; fi
  - cd dist

deploy:
  - provider: azure_web_apps
    username: $FTP_USER
    password: $FTP_PASSWORD
    site: testimdino
    slot: style
    on:
      branch: prod
  - provider: npm
    tag: latest
    all_branches: true
    skip_cleanup: true
    on:
      branch: prod
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
  - provider: npm
    tag: next
    on:
      branch: master
    all_branches: true
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
